"""Opt-in end-to-end checks against real tools, never mocks of conversion.

Set DOVI_TEST_FIXTURE to a small, disposable Profile 7 MEL fixture generated by
scripts/make_test_fixture.py. Each operation writes into pytest's temporary tree.
"""
import hashlib
import os
import shutil
import tarfile
import io
import json
import threading
from dataclasses import replace
from pathlib import Path

import pytest

from dovi_studio.dependencies import discover, require
from dovi_studio.engine import Engine, verify_inventory
from dovi_studio.models import Cancelled, OperationError, Options, Skipped
from dovi_studio.process import Runner

pytestmark = pytest.mark.integration


@pytest.fixture
def media_tools():
    if not os.environ.get('DOVI_TEST_FIXTURE'):
        pytest.skip('Set DOVI_TEST_FIXTURE for real conversion tests')
    tools = discover()
    require(tools, 'stream')
    return tools


@pytest.fixture
def source(tmp_path, media_tools):
    target = tmp_path / 'Café, source [1].mkv'
    shutil.copyfile(os.environ['DOVI_TEST_FIXTURE'], target)
    return target


@pytest.mark.parametrize('method,mode', [('disk', 'p81'), ('stream', 'p81'), ('disk', 'hdr10')])
def test_conversion_preserves_tracks_and_original(source, media_tools, tmp_path, method, mode):
    before = hashlib.sha256(source.read_bytes()).hexdigest()
    engine = Engine(media_tools, Options(output_dir=str(tmp_path / 'result'), method=method, mode=mode))
    output, analysis = engine.convert(source)
    assert analysis.full and analysis.verdict == 'mel'
    original, converted = engine.probe(source), engine.probe(output)
    verify_inventory(original, converted)
    assert converted.profile == (8 if mode == 'p81' else None)
    if mode == 'p81':
        assert converted.compatibility == 1
    assert hashlib.sha256(source.read_bytes()).hexdigest() == before
    assert not list((tmp_path / 'result').glob('.dovi-studio-*'))
    with pytest.raises(Skipped, match='already exists'):
        engine.convert(source)


def test_archive_and_restore_roundtrip(source, media_tools, tmp_path):
    engine = Engine(media_tools, Options(output_dir=str(tmp_path / 'result'), backup_el=True))
    output, _ = engine.convert(source)
    restored = engine.restore(output, output.with_suffix('.dovi'))
    assert engine.probe(restored).profile == 7
    verify_inventory(engine.probe(source), engine.probe(restored))


def test_mediainfo_fallback_without_ffmpeg_or_ffprobe(source, media_tools, tmp_path):
    tools = dict(media_tools)
    for name in ('ffmpeg', 'ffprobe'):
        tools[name] = replace(tools[name], ok=False)
    engine = Engine(tools, Options(output_dir=str(tmp_path / 'result')))
    output, _ = engine.convert(source)
    assert engine.probe(output).profile == 8


def test_standalone_layer_backup(source, media_tools, tmp_path):
    engine = Engine(media_tools, Options(output_dir=str(tmp_path / 'result')))
    archive = engine.backup(source)
    assert archive.stat().st_size > 0
    output, _ = engine.convert(source)
    assert engine.probe(engine.restore(output, archive)).profile == 7


def test_cancel_during_conversion_preserves_source_and_cleans_work(source, media_tools, tmp_path):
    cancel = threading.Event()
    work, output = tmp_path / 'work', tmp_path / 'out'
    before = source.read_bytes()
    def progress(stage, value):
        if stage == 'Extracting original video':
            cancel.set()
    engine = Engine(media_tools, Options(temp_dir=str(work), output_dir=str(output)), Runner(cancel), progress)
    with pytest.raises(Cancelled):
        engine.convert(source)
    assert source.read_bytes() == before
    assert not list(work.iterdir())
    assert not list(output.iterdir())


def test_wrong_base_archive_rejected(source, media_tools, tmp_path):
    engine = Engine(media_tools, Options(output_dir=str(tmp_path / 'result'), backup_el=True))
    output, _ = engine.convert(source)
    archive_path = output.with_suffix('.dovi')
    wrong = tmp_path / 'wrong.dovi'
    with tarfile.open(archive_path) as archive, tarfile.open(wrong, 'w') as target:
        for member in archive:
            data = archive.extractfile(member).read()
            if member.name == 'manifest.json':
                manifest = json.loads(data)
                manifest['base_sha256'] = '0'*64
                data = json.dumps(manifest).encode()
            replacement = tarfile.TarInfo(member.name)
            replacement.size = len(data)
            target.addfile(replacement, io.BytesIO(data))
    with pytest.raises(OperationError, match='does not match'):
        engine.restore(output, wrong)
    assert not list((tmp_path / 'result').glob('*.restored.mkv'))


def test_real_fel_inspection_and_policy(media_tools, tmp_path):
    source = os.environ.get('DOVI_TEST_FEL_FIXTURE')
    if not source:
        pytest.skip('Set DOVI_TEST_FEL_FIXTURE for FEL checks')
    engine = Engine(media_tools, Options(output_dir=str(tmp_path)))
    media = engine.probe(Path(source))
    analysis = engine.inspect(media, full=True)
    assert analysis.verdict == 'fel'
    assert 600 < analysis.peak_nits < 650
    with pytest.raises(Skipped, match='FEL is excluded'):
        engine.convert(Path(source))
    assert engine.inspect(replace(media, max_cll=200), full=True).verdict == 'complex'
    assert engine.inspect(replace(media, max_cll=None), full=True).verdict == 'unknown'
    engine.options.include_fel = True
    output, _ = engine.convert(Path(source))
    assert engine.probe(output).profile == 8


def test_gui_conversion_worker_end_to_end(source, media_tools, tmp_path, monkeypatch):
    import time
    from PySide6.QtWidgets import QApplication, QMessageBox
    from dovi_studio import settings
    from dovi_studio.ui import MainWindow
    monkeypatch.setattr(settings, 'settings_dir', lambda: tmp_path / 'config')
    failures = []
    monkeypatch.setattr(QMessageBox, 'warning', lambda parent, title, message: failures.append(message))
    app = QApplication.instance() or QApplication([])
    window = MainWindow(check_tools=False)
    window.options.output_dir = str(tmp_path / 'output')
    window.add_discovered([(source, None)])
    window.open_conversion()
    wizard = window.conversion_wizard
    wizard.next()
    wizard.next()
    wizard.next()
    deadline = time.monotonic() + 30
    while not wizard.progress_page.done and time.monotonic() < deadline:
        app.processEvents()
        time.sleep(0.01)
    assert not failures
    assert window.worker is None
    assert window.jobs[0].status == 'Done', window.jobs[0].result
    assert Path(window.jobs[0].result).is_file()
    assert wizard.progress_page.done
    wizard.accept()
    window.close()


def test_variable_timestamps_and_video_tags(source, media_tools, tmp_path):
    import xml.etree.ElementTree as ET
    engine = Engine(media_tools, Options(output_dir=str(tmp_path / 'result')))
    timestamps = tmp_path / 'variable.txt'
    value = 125.0
    values = []
    for frame in range(260):
        values.append(str(value))
        value += 40 if frame % 3 else 48
    timestamps.write_text('# timestamp format v2\n' + '\n'.join(values) + '\n')
    tags = tmp_path / 'tags.xml'
    tags.write_text('<Tags><Tag><Targets/><Simple><Name>COMMENT</Name><String>Preserve this video note</String></Simple></Tag></Tags>')
    vfr = tmp_path / 'variable-source.mkv'
    engine.run('mkvmerge', '-o', vfr, '--timestamps', f'0:{timestamps}', '--tags', f'0:{tags}', source)
    output, _ = engine.convert(vfr)
    output_tags = tmp_path / 'output-tags.xml'
    engine.run('mkvextract', output, 'tags', output_tags)
    assert any(node.text == 'Preserve this video note' for node in ET.parse(output_tags).iter('String'))


def test_ffprobe_without_mediainfo(source, media_tools, tmp_path):
    tools = dict(media_tools)
    tools['mediainfo'] = replace(tools['mediainfo'], ok=False)
    engine = Engine(tools, Options(output_dir=str(tmp_path / 'result')))
    output, _ = engine.convert(source)
    assert engine.probe(output).compatibility == 1
